### ISSUE TITLE
data is disappear

### ISSUE THREAD

**Issue by zhanhuanli** [anxiangSir/deeplab_v3#1]
你好，我想请问百度云盘的数据消失了，请问您能提供重新提供一份数据吗？万分感激~

**Comment by anxiangsir** [comment]
请问你指的是train文件夹中没有数据吗，train中的数据由preprocess.py生成，原始数据在origin中

**Comment by zhanhuanli** [comment]
好的，我大意了~  谢谢~  
    # 载入残差网络预训练好的权重
    restorer.restore(sess,'net/resnet_model/resnet_v2_50.ckpt')
这里是不是没有这个resnet的预训练文件呀，我一直跑不通。。。

**Comment by anxiangsir** [comment]
sorry，我忘了贴预训练模型的地址，预训练模型的地址在这里
https://github.com/tensorflow/models/tree/master/research/slim
下载resnet_v2_50.ckpt
你也可以注掉从头训练

**Comment by zhanhuanli** [comment]
好的~ 谢谢你~ 最近由于出了v3+，所以想看看deeplab系列~ 那我明天试试，麻烦啦

**Comment by zhanhuanli** [comment]
@anxiangSir  安翔君， 我想请教一个问题。
global_step = tf.Variable(0, trainable=False)
train_op = optimizer.minimize(loss=self.loss,global_step=global_step)
.....
saver.save(sess, save_path=ckpt_path,global_step=global_step.eval())
恢复中断模型后，global_step的次数依旧从0次开始迭代，但是此时的loss曲线图将不会连续绘制。请问有什么办法可以解决这个问题？这里的global_step变量值为什么无法存入ckpt中？安翔君，你当时训练是如何解决的呢？
