### ISSUE TITLE
关于运行main.py错误

### ISSUE THREAD

**Issue by Tangtyone** [anxiangSir/deeplab_v3#11]
你好，我运行main.py显示错误。能帮我看看原因吗？
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'ckpt/deeplab_v3/'

![default](https://user-images.githubusercontent.com/35962229/50973342-9b985080-1523-11e9-82c0-5e357e0fa095.png)

**Comment by anxiangsir** [comment]
抱歉~这个 92行这个os.mkdir(model_path) 新建文件夹出问题了，你可以手动新建一个文件夹，我去修改一下代码

**Comment by anxiangsir** [comment]
你可以改成这个函数~
```
import os
os.makedirs()
```

**Comment by Tangtyone** [comment]
十分感谢你的帮助。但我运行已经改了的代码，还是有些问题。第一次运行模型，有很多地方不懂，能帮我解答一下吗？
![default](https://user-images.githubusercontent.com/35962229/51015223-5c5f1380-15a6-11e9-937a-ea0d570c2c0e.png)
