### ISSUE TITLE
How to modify the prediction program so that its output image is as large as the original image？怎么修改预测程序让其输出图像和原始图像一样？大

### ISSUE THREAD

**Issue by Newanimalfarm1984** [anxiangSir/deeplab_v3#12]
我在测试图像像素精度和MIOU发现预测图像比原始图像要小，似乎是因为切图是把不能整除部分给忽略了，有什么办法能让输出结果能和原始图像一样大小？I tested the image pixel precision and MIOU found that the predicted image is smaller than the original image. It seems that the cut image is negligible for the incomplete part. Is there any way to make the output the same size as the original image?

**Comment by anxiangsir** [comment]
的确是我裁图的时候忽略了~对256除整，你可以事先将要测试的图片padding成256的倍数，然后预测完之后将多出的那部分裁去

**Comment by Newanimalfarm1984** [comment]
感谢了，我没想到这一点。开始一直在predict程序里修改代码想padding成能整除size，可是代码一直没修改好，装进牛角尖里(>﹏<)。

**Comment by anxiangsir** [comment]
是我代码写的坑😂
