### ISSUE TITLE
If a decoder was added, will it work better?

### ISSUE THREAD

**Issue by bluemoonwencong** [anxiangSir/deeplab_v3#16]
这个实现在 encoder之后直接用 tf.image.resize_bilinear 把 (None, 16, 16, 5)的tensor转为 (None, 256, 256, 5),  16倍还原，，用deeplabv3 paper的解码器，分两次4倍还原会不会更好呢。。

**Comment by anxiangsir** [comment]
我觉得会的，这就是v3+的做法，你可以试试
