### ISSUE TITLE
为什么main.py的resnet pretrain被注释掉了？

### ISSUE THREAD

**Issue by MarkYangjiayi** [anxiangSir/deeplab_v3#17]
如题，描述里不是说训练时使用resnet50的预训练么

**Comment by anxiangsir** [comment]
需要目录下有该文件，如果没有就会报错，为了防止报错，我注释掉了这行代码，自己根据需要可以去下载预训练的文件

**Comment by MarkYangjiayi** [comment]
@anxiangSir 哦哦，谢谢～另外项目需要我把你的代码改成TFRecord输入数据集了，过两天PR一下。另外我看您在TODO里提到了消除拼接问题，根据以前的经验可以在裁切图片时加入overlap，然后在predict拼接时使用网络输出的logits作为输入然后在overlap取概率平均然后再argmax。这样应该可以很好的消除拼接问题，可以参考一下

**Comment by anxiangsir** [comment]
哈哈，这个问题昨天面试官问到我了，我明白你的意思

**Comment by Tangtyone** [comment]
@MarkYangjiayi  请问消除拼接问题，怎么裁切图片时加入overlap

**Comment by MarkYangjiayi** [comment]
@Tangtyone 说白了就是你decoder在predict哪类之前输出的是pixel-wise的每类的概率。加入overlap就是说你在一开始截图的时候时候边界留有富裕，相邻的两个图之间的边界有重合，具体多少你自己试试吧。关键在于拼接的时候传统操作是先predict后拼接。用overlap的话就是先用概率矩阵拼接，然后输出大图。这样做的优势是边界的拼接部分更圆滑（因为重合部分相当于是综合了两张图片的概率），不会有明显的割裂感。如果我没说清楚可以再问

**Comment by HuangQinJian** [comment]
> @Tangtyone 说白了就是你decoder在predict哪类之前输出的是pixel-wise的每类的概率。加入overlap就是说你在一开始截图的时候时候边界留有富裕，相邻的两个图之间的边界有重合，具体多少你自己试试吧。关键在于拼接的时候传统操作是先predict后拼接。用overlap的话就是先用概率矩阵拼接，然后输出大图。这样做的优势是边界的拼接部分更圆滑（因为重合部分相当于是综合了两张图片的概率），不会有明显的割裂感。如果我没说清楚可以再问

请问有这部分的代码吗？求共享

**Comment by HuangQinJian** [comment]
> 需要目录下有该文件，如果没有就会报错，为了防止报错，我注释掉了这行代码，自己根据需要可以去下载预训练的文件

请问能提供下载地址吗？以及如果换掉backbone需要修改什么么？

**Comment by MarkYangjiayi** [comment]
@HuangQinJian 你要的文件在readme里就有...Overlap的那个我手头没代码，其实按照我写的那个逻辑实现一下应该不太难...
