### ISSUE TITLE
使用其他数据的问题

### ISSUE THREAD

**Issue by Tangtyone** [anxiangSir/deeplab_v3#21]
我使用其他数据跑这个模型，数据预测时出现问题。这问题能怎么解决吗？
![%~6~}$TD7QM2Q2VBDUNG{L](https://user-images.githubusercontent.com/35962229/58521933-df4cd780-81f0-11e9-9111-4b53201804ab.png)
![O 6 EB)G%6G5H}}Z(YXJUG](https://user-images.githubusercontent.com/35962229/58521936-e07e0480-81f0-11e9-8a85-11f8c11c5f92.png)

**Comment by zhy788** [comment]
你好，我也是用了其他的数据（ISPRS）训练后一张图都是白色，请问是什么问题呢，想问下您的问题有没有得到解决啊。

**Comment by Angel0003** [comment]
> 你好，我也是用了其他的数据（ISPRS）训练后一张图都是白色，请问是什么问题呢，想问下您的问题有没有得到解决啊。

請問你怎麼測試自己的數據的

**Comment by SdustZhangzhen** [comment]
@Tangtyone @zhy788 @anxiangsir @ximimiao 请问使用自己的数据集，就像层主说的ISPRS，其IOU一直是0，是什么原因呢？
