### ISSUE TITLE
hello, a question

### ISSUE THREAD

**Issue by zhengkai17** [anxiangSir/deeplab_v3#23]
how to train it with my own dataset ? thx

**Comment by zhengkai17** [comment]
ValueError: Cannot feed value of shape (4,) for Tensor 'input_x:0', which has shape '(?, 256, 256, 3)'
how to solve this problem when I throw in my own dataset in the origin file ?

**Comment by leezhang2** [comment]
我也遇到了同样的问题请问你解决了吗
