### ISSUE TITLE
please help me ? what is the problem

### ISSUE THREAD

**Issue by zhengkai17** [anxiangSir/deeplab_v3#24]
File "/home/zhengkai/anaconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/utils/validation.py", line 205, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [4305684, 1435228]

**Comment by ke-22** [comment]
> File "/home/zhengkai/anaconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/utils/validation.py", line 205, in check_consistent_length
> " samples: %r" % [int(l) for l in lengths])
> ValueError: Found input variables with inconsistent numbers of samples: [4305684, 1435228]

你好，我也遇到了类似的问题，即输入维度与设定维度不符，请问您解决了吗
