### ISSUE TITLE
train 耗时

### ISSUE THREAD

**Issue by leezhang2** [anxiangSir/deeplab_v3#26]
请问一下我的电脑配置是两块1080Ti，但是运行train文件时，运行好久都没有反应，第一次迭代的结果都没有出来，我需要继续等待吗？

**Comment by Newanimalfarm1984** [comment]
我用1080训练20万次大概5天时间

**Comment by leezhang2** [comment]
我的1080根本没有办法训练啊





| |
张力
|
|
邮箱：leezhang2@163.com
|

签名由 网易邮箱大师 定制

在2019年07月15日 10:46，Newanimalfarm1984 写道：

我用1080训练20万次大概5天时间

**Comment by Newanimalfarm1984** [comment]
我把batch_size =4就可以运行了，代码提供者显卡是16G大小的特斯拉v100，这个比不了
