### ISSUE TITLE
opencv 版本

### ISSUE THREAD

**Issue by cendelian** [anxiangSir/deeplab_v3#29]
你好，请问opencv版本号是多少？
我运行报错
cv2.CAP_MODE_RGB
cv2.CAP_MODE_GRAY
显示没有

**Comment by anxiangsir** [comment]
pip install opencv-python==3.4.2.17
readme已更新

**Comment by Freezinghot** [comment]
新版本的opencv是
cv2.IMREAD_COLOR
cv2.IMREAD_GRAYSCALE
