### ISSUE TITLE
关于标签

### ISSUE THREAD

**Issue by linydf** [anxiangSir/deeplab_v3#3]
您好，刚开始接触分割，请问如何训练自己的数据，之前用labelme标注会生成标签二值图像，但是在您分享的数据集里面标签为什么都看不到？希望得到您的解答，祝好！！！

**Comment by anxiangsir** [comment]
这个任务是5分类任务，标签中每个像素点通过8位的灰度值来表示。值的取值是（0 - 4），都接近黑色，看的不是很清楚，你可以加我QQ一起交流

**Comment by anxiangsir** [comment]
1363090802
