### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'CAP_MODE_RGB'

### ISSUE THREAD

**Issue by wwwmmmqqq** [anxiangSir/deeplab_v3#30]
File "D:\workspace\deeplabv3-Tensorflow\data_utils.py", line 63, in read_path
    x.append(self.transform(cv2.imread(x_path[i], cv2.CAP_MODE_RGB)))
AttributeError: module 'cv2.cv2' has no attribute 'CAP_MODE_RGB'

plaese,help me,Thank you!

**Comment by Angel0003** [comment]
cv2.CAP_MODE_RGB改成cv2.IMREAD_COLOR，cv2.CAP_MODE_GRAY改成cv2.IMREAD_GRAYSCALE

**Comment by wwwmmmqqq** [comment]
好的，谢谢啦，可以解决



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Angel0003"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 中午11:21
收件人: "ximimiao/deeplabv3-Tensorflow"<deeplabv3-Tensorflow@noreply.github.com&gt;; 
抄送: "W"<1059257750@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ximimiao/deeplabv3-Tensorflow] AttributeError: module &#39;cv2.cv2&#39; has no attribute &#39;CAP_MODE_RGB&#39; (#30)




cv2.CAP_MODE_RGB改成cv2.IMREAD_COLOR，cv2.CAP_MODE_GRAY改成cv2.IMREAD_GRAYSCALE

**Comment by anxiangsir** [comment]
cuda==8.0
cudnn==6
python==3.5
pip install opencv-python==3.4.2.17
pip install tensorflow-gpu==1.13.1
pip install sklearn
pip install pandas

更新了一个requirement、用这个就没有问题了
