### ISSUE TITLE
训练自己数据 IOU一直为0

### ISSUE THREAD

**Issue by SdustZhangzhen** [anxiangSir/deeplab_v3#32]
对作者提供的数据进行训练，结果较好。但换成自己数据进行训练时，类别数增加1类，在训练时，IOU一直为0，是什么原因呢？数据的问题？
======================100======================
IOU_其他/other                            0.2358
IOU_植物/plant                            0.0000
IOU_道路/road                             0.0000
IOU_建筑/arch                             0.0000
IOU_水体/water                            0.0000
IOU_背景/Banckground                 0.0000
iou                                     0.0393
accuracy                                0.2348

**Comment by ke-22** [comment]
> 对作者提供的数据进行训练，结果较好。但换成自己数据进行训练时，类别数增加1类，在训练时，IOU一直为0，是什么原因呢？数据的问题？
> ======================100======================
> IOU_其他/other 0.2358
> IOU_植物/plant 0.0000
> IOU_道路/road 0.0000
> IOU_建筑/arch 0.0000
> IOU_水体/water 0.0000
> IOU_背景/Banckground 0.0000
> iou 0.0393
> accuracy 0.2348

你好，请问分类的类别在哪里更改呢
