### ISSUE TITLE
拼接问题

### ISSUE THREAD

**Issue by yijian-stack** [anxiangSir/deeplab_v3#36]
我代码水平菜，按我的理解，是把影像切割，训练，预测，拼接。训练的越多，拼接的效果越好。那拼接的意思就是直接硬拼是吗，我感觉那就是concat这个函数解决的拼接问题对吗？就像两个矩阵拼在一起一样，是吗？感谢解答疑惑。

**Comment by anxiangsir** [comment]
是的，硬拼

发自我的 iPhone

在 2023年2月7日，15:49，不夜候 ***@***.***> 写道：

﻿

我代码水平菜，按我的理解，是把影像切割，训练，预测，拼接。训练的越多，拼接的效果越好。那拼接的意思就是直接硬拼是吗，我感觉那就是concat这个函数解决的拼接问题对吗？就像两个矩阵拼在一起一样，是吗？感谢解答疑惑。
