### ISSUE TITLE
Can you offer the trained model

### ISSUE THREAD

**Issue by MountainOne** [anxiangSir/deeplab_v3#7]
I want to run the model directly in my environment, so can you offer it? 
Thank you very much.

**Comment by anxiangsir** [comment]
当然可以啊，自动化所的大佬

**Comment by anxiangsir** [comment]
你等我重新train一个

**Comment by MountainOne** [comment]
hhhh, 谢谢了。

**Comment by anxiangsir** [comment]
但我这个模型估计只适用于我的任务，换个数据集估计就不行了

**Comment by MountainOne** [comment]
这我明白，我就是想看看效果，我们也有类似的任务

**Comment by anxiangsir** [comment]
链接:https://pan.baidu.com/s/1DDr8zdOFFrMLw-T8v_AP0A  密码:ir5x
