### ISSUE TITLE
关于test？

### ISSUE THREAD

**Issue by GeneralLi95** [anxiangSir/deeplab_v3#9]
想请教一下如何进行test

**Comment by anxiangsir** [comment]
我的测试集没有标签，所以没法测试

**Comment by GeneralLi95** [comment]
@anxiangSir 谢谢，想问的是，根据一张现有图片，如何通过模型计算，得到分割后的结果。想拿您的方案，在CVPR DeepGlobe 2018 数据集上做做试试

**Comment by anxiangsir** [comment]
你加我QQ：1363090802

**Comment by Angel0003** [comment]
請教一下，你的測試代碼是哪個，怎麼測試下自己的圖片，看看在我的數據集上的效果
